In [1]:
import numpy as np

In [2]:
# More data types
# Casting
# “Bigger” type wins in mixed-type operations:

In [3]:
np.array([1,2,3])+1.5

array([ 2.5,  3.5,  4.5])

In [4]:
a=np.array([1,2,3])
a.dtype

dtype('int32')

In [5]:
a[0]=1.9# <-- float is truncated to integer
a

array([1, 2, 3])

In [7]:
# Forced casts:
a = np.array([1.7, 1.2, 1.6])
b=a.astype(int)# <-- truncates to integer
b

array([1, 1, 1])

In [10]:
# Rounding:
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
b # still floating-point

array([ 1.,  2.,  2.,  2.,  4.,  4.])

In [12]:
c=b.astype(int)
c

array([1, 2, 2, 2, 4, 4])

In [13]:
# Integers (signed):
# int8 8 bits
# int16 16 bits
# int32 32 bits (same as int on 32-bit platform)
# int64 64 bits (same as int on 64-bit platform)
# doubt

In [ ]:
#skip