In [2]:
# Numpy arrays-Memory-efficient container that provides fast numerical operations.


In [3]:
import numpy as np
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [4]:
L=range(100)
%timeit [i**2 for i in L]

100000 loops, best of 3: 7.83 µs per loop


In [5]:
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
%timeit a**2

The slowest run took 30.51 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 810 ns per loop


In [7]:
np.array?

In [8]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArray.__new__
    Create a new masked array from scratch.
numpy.lib.ar

In [9]:
np.con*?

In [10]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
a.ndim

1

In [12]:
a.shape

(4L,)

In [13]:
len(a)

4

In [14]:
b=np.array([[1,2,3,4],[4,5,6,7]])
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [15]:
b.ndim

2

In [16]:
b.shape

(2L, 4L)

In [17]:
len(b)#returns the size of the first dimension

2

In [18]:
# c=np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
# c

In [19]:
# c.shape

In [20]:
# len(c)

In [21]:
#arrange-Evenly spaced:

In [22]:
a=np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
b=np.arange(0,8,2)#last one exclusive
b

array([0, 2, 4, 6])

In [24]:
# linspace-by number of points:

In [25]:
c=np.linspace(0,1,7)
c

array([ 0.        ,  0.16666667,  0.33333333,  0.5       ,  0.66666667,
        0.83333333,  1.        ])

In [26]:
c=np.linspace(0,1,7,endpoint=False)
c

array([ 0.        ,  0.14285714,  0.28571429,  0.42857143,  0.57142857,
        0.71428571,  0.85714286])

In [27]:
# ones,zeroes,diag,eye

In [28]:
a=np.ones((3,3))# reminder: (3, 3) is a tuple
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [29]:
b=np.zeros((2,2))
b

array([[ 0.,  0.],
       [ 0.,  0.]])

In [30]:
c=np.eye(3)
c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [31]:
d=np.diag(np.array([1,2,3]))
d

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [32]:
d[1, 1]

2

In [33]:
d[2, 1] = 10

In [34]:
d

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0, 10,  3]])

In [35]:
d[1]

array([0, 2, 0])

In [36]:
np.random.rand(4) # uniform in [0, 1]

array([ 0.51985942,  0.25193939,  0.98397519,  0.80230265])

In [37]:
np.random.randn(4) # Gaussian

array([ 0.86778532, -0.27452093, -0.33221444,  0.40557672])

In [38]:
np.random.seed(124) # Setting the random seed

In [39]:
# Basic data types in numpy

In [40]:
a = np.array([1, 2, 3])
a.dtype

dtype('int32')

In [41]:
a = np.array([1., 2., 3.])
a.dtype

dtype('float64')

In [42]:
a = np.array([1, 2, 3], dtype=float)#You can explicitly specify which data-type you want:
a.dtype

dtype('float64')

In [43]:
# The default data type is floating point:
a = np.ones((3, 3))
a.dtype

dtype('float64')

In [44]:
a = np.array([1+2j, 3+4j, 5+6*1j])
a.dtype

dtype('complex128')

In [45]:
a = np.array([True, False, False, True])
a.dtype

dtype('bool')

In [46]:
a = np.array(['Bonjour', 'Hello', 'Hallo',])#strings containing max. 7 letters
a.dtype

dtype('S7')

In [47]:
# Indexing and slicing in array

In [48]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a[0],a[1],a[-1]

(0, 1, 9)

In [50]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [51]:
    d=np.arange(1,2,3)

In [52]:
a=np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [53]:
a=a.reshape(6,6)

In [54]:
a[0,1]

1

In [55]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [56]:
a[0,3:5]

array([3, 4])

In [57]:
a[3,[0,2,5]]

array([18, 20, 23])

In [58]:
a[4:,4:]

array([[28, 29],
       [34, 35]])

In [59]:
a[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [60]:
a[::2,::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [61]:
a[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [62]:
# combine assignment and slicing:

In [63]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a[5:]=10

In [65]:
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [66]:
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [67]:
np.arange(0,51,10)[:,np.newaxis]+np.arange(6)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [68]:
is_prime=np.ones((100,),dtype=bool)

In [69]:
is_prime

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [70]:
a=[1,2,3,4,5,6,7,8,9,10]
a[4::2]

[5, 7, 9]

In [71]:
is_prime[:2]=0

In [72]:
is_prime

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [73]:
N_max=int(np.sqrt(len(is_prime)))
for j in range(2,N_max):
    is_prime[2*j::j]=False

In [74]:
is_prime

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False, False], dtype=bool)

In [75]:
np.random.rand

<function rand>

In [76]:
#Fancy indexing-Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks).
#It creates copies not views.

In [77]:
# Using boolean masks

In [78]:
np.random.seed(3)
a=np.random.random_integers(0,20,15)
a

C:\Users\ashis.panda\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  from ipykernel import kernelapp as app


array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [79]:
mask=(a%3==0)
mask

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False], dtype=bool)

In [80]:
a[a%3==0]

array([ 3,  0,  9,  6,  0, 12])

In [81]:
# Indexing with a mask can be very useful to assign a new value to a sub-array:

In [82]:
a[a%3==0]=-1
a

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, 20, -1,  7, 14])

In [83]:
# Indexing with an array of integers

In [84]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [85]:
a[1:3]

array([10, 20])

In [86]:
# Indexing can be done with an array of integers, where the same index is repeated several time:

In [87]:
a[[2,3,4,2,1]]

array([20, 30, 40, 20, 10])

In [88]:
a[[9,7]]=-100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

In [89]:
# When a new array is created by indexing with an array of integers, the new array has the same 
# shape than the array of integers:

In [90]:
np.random.seed(3)
a=np.random.random_integers(0,20,15)
idx=np.array([[3,5],[7,8]]) #elements will be used for indexing
a[idx] #elements at those index

C:\Users\ashis.panda\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  from ipykernel import kernelapp as app


array([[ 0, 10],
       [ 9, 10]])

In [91]:
idx.shape

(2L, 2L)

In [92]:
np.arange(0,51,10)[:,np.newaxis]+np.arange(6)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [93]:
np.arange(0,51,10)

array([ 0, 10, 20, 30, 40, 50])

In [94]:
np.arange(0,51,10)+np.arange(6)

array([ 0, 11, 22, 33, 44, 55])

In [95]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [96]:
np.newaxis?

In [97]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])
x1.shape

(5L,)

In [98]:
x1[ np.newaxis,:].shape#np.newaxis increases the dimension of array

(1L, 5L)

In [99]:
x1[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [100]:
x1[:, np.newaxis]+x2

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [101]:
a=np.arange(0,51,10)[:,np.newaxis]+np.arange(6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [102]:
a[(0,1,2,3,4),(1,2,3,4,5)] #only the index , combination of which is taken

array([ 1, 12, 23, 34, 45])

In [103]:
a[3:,[0,2,5]]#after 3rd row every rows 0,2,5 columns

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [104]:
a[[0,2,5],3] #3rd row 0,2,5 columns

array([ 3, 23, 53])

In [105]:
# Numerical operations on arrays

In [106]:
# Elementwise operations

In [107]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [108]:
2**a #to the power

array([ 2,  4,  8, 16])

In [109]:
b=np.ones(4)+1 #type casting 1
a-b

array([-1.,  0.,  1.,  2.])

In [110]:
type(np.ones(4)[1])

numpy.float64

In [111]:
a*b

array([ 2.,  4.,  6.,  8.])

In [112]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [113]:
j=np.arange(5)
2**(j+1)-j

array([ 2,  3,  6, 13, 28])

In [114]:
c=np.ones((3,3))
c

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [115]:
c*c #array multiplication

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [116]:
c.dot(c)#matrix multiplication!

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [117]:
# Array-wise comparisons:

In [118]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a==b

array([False,  True, False,  True], dtype=bool)

In [119]:
a>b

array([False, False,  True, False], dtype=bool)

In [120]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [121]:
np.array_equal(a,b)

False

In [122]:
np.array_equal(a,c)

True

In [123]:
# Logical operations:

In [124]:
a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False], dtype=bool)

In [125]:
np.logical_and(a,b)

array([ True, False, False, False], dtype=bool)

In [126]:
# Transcendental functions:

In [127]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [128]:
np.log(a)

array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436])

In [129]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [130]:
np.ones((3,3))+1

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [131]:
a=np.triu(np.ones((3,3)),1)
a

array([[ 0.,  1.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [132]:
a.T

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  1.,  0.]])

In [133]:
a+=a.T
a

array([[ 0.,  1.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  1.,  0.]])

In [134]:
# Computing sums

In [135]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [136]:
x.sum()

10

In [137]:
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [138]:
x.sum(axis=0) #columns first dimension

array([3, 3])

In [139]:
x.sum(axis=1) #rows 2nd dimension

array([2, 4])

In [140]:
x[0,:].sum(),x[1,:].sum() #0th row all elements and 1st row all elements sum

(2, 4)

In [141]:
x=np.array([1,3,2])
x.min()

1

In [142]:

x.max()

3

In [143]:
x.argmin()

0

In [144]:
x.argmax()

1

In [145]:
np.all([True,True,False])

False

In [146]:
np.any([True,True,False])

True

In [147]:
np.all([True,True,True])

True

In [148]:
# Can be used for array comparisons:

In [149]:
a = np.zeros((100, 100))

In [150]:
np.any(a != 0)

False

In [151]:
np.all(a == a)

True

In [152]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [153]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

In [154]:
x.mean()

1.75

In [155]:
np.median(y,axis=-1)

array([ 2.,  5.])

In [156]:
x.std()

0.82915619758884995

In [157]:
!cat data/populations.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [158]:
data = np.loadtxt('C:\\Users\\ashis.panda\\Desktop\\popul.txt')

In [159]:
data

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

In [160]:
data.T

array([[  1900.,   1901.,   1902.,   1903.,   1904.,   1905.,   1906.,
          1907.,   1908.,   1909.,   1910.,   1911.,   1912.,   1913.,
          1914.,   1915.,   1916.,   1917.,   1918.,   1919.,   1920.],
       [ 30000.,  47200.,  70200.,  77400.,  36300.,  20600.,  18100.,
         21400.,  22000.,  25400.,  27100.,  40300.,  57000.,  76600.,
         52300.,  19500.,  11200.,   7600.,  14600.,  16200.,  24700.],
       [  4000.,   6100.,   9800.,  35200.,  59400.,  41700.,  19000.,
         13000.,   8300.,   9100.,   7400.,   8000.,  12300.,  19500.,
         45700.,  51100.,  29700.,  15800.,   9700.,  10100.,   8600.],
       [ 48300.,  48200.,  41500.,  38200.,  40600.,  39800.,  38600.,
         42300.,  44500.,  42100.,  46000.,  46800.,  43800.,  40900.,
         39400.,  39000.,  36700.,  41800.,  43300.,  41300.,  47300.]])

In [161]:
year, hares, lynxes, carrots = data.T# trick: columns to variables

In [162]:
# from matplotlib import pyplot as plt

In [163]:
# plt.plot(year, hares, year, lynxes, year, carrots)

In [164]:
# Broadcasting


In [165]:
# Basic operations on numpy arrays (addition, etc.) are elementwise

In [166]:
# This works on arrays of the same size.
# Nevertheless, It’s also possible to do operations on arrays of different
# sizes if Numpy can transformthese arrays so that they all have
# the same size: this conversion is called broadcasting.
# The image below gives an example of broadcasting:

In [167]:
#Variation for tile

In [168]:
a=np.array([0,1,2])
np.tile(a,2)

array([0, 1, 2, 0, 1, 2])

In [169]:
np.tile(a,(2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [170]:
b = np.array([[1, 2], [3, 4]])
np.tile(b,2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [171]:
np.tile(b,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [172]:
np.tile(np.arange(0,40,10),(3,1))

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [173]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
b = np.array([0, 1, 2])

In [174]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [175]:
a=np.ones((4,5))

In [176]:
a[0]=2 #assign 0th dimension as 2

In [177]:
a


array([[ 2.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [178]:
a=np.arange(0, 40, 10)
a.shape

(4L,)

In [179]:
a=a[:,np.newaxis]

In [180]:
a.shape

(4L, 1L)

In [181]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [182]:
b

array([0, 1, 2])

In [183]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [184]:
# Broadcasting seems a bit magical, but it is actually quite natural to use it when we want to solve a problem
# whose output data is an array with more dimensions than input data.

In [185]:
# Worked Example: Broadcasting
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])


In [186]:
distance_array=np.abs(mileposts-mileposts[:,np.newaxis])
distance_array

array([[   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448],
       [ 198,    0,  105,  538,  673,  977, 1277, 1346, 1715, 2250],
       [ 303,  105,    0,  433,  568,  872, 1172, 1241, 1610, 2145],
       [ 736,  538,  433,    0,  135,  439,  739,  808, 1177, 1712],
       [ 871,  673,  568,  135,    0,  304,  604,  673, 1042, 1577],
       [1175,  977,  872,  439,  304,    0,  300,  369,  738, 1273],
       [1475, 1277, 1172,  739,  604,  300,    0,   69,  438,  973],
       [1544, 1346, 1241,  808,  673,  369,   69,    0,  369,  904],
       [1913, 1715, 1610, 1177, 1042,  738,  438,  369,    0,  535],
       [2448, 2250, 2145, 1712, 1577, 1273,  973,  904,  535,    0]])

In [187]:
#x, y = np.arange(5), np.arange[:, np.newaxis]

In [188]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]

In [189]:
x

array([0, 1, 2, 3, 4])

In [190]:
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [191]:
distance=np.sqrt(x**2+y**2)
distance

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ],
       [ 4.        ,  4.12310563,  4.47213595,  5.        ,  5.65685425]])

In [192]:
%matplotlib inline
plt.pcolor(distance)
plt.colorbar()

NameError: name 'plt' is not defined

In [193]:
# the numpy.ogrid function allows to directly create vectors x and y of the previous example, with two
# # “significant dimensions”:

In [194]:
x,y=np.ogrid[0:5,0:5]

In [195]:
x,y

(array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]]))

In [196]:
x.shape, y.shape

((5L, 1L), (1L, 5L))

In [197]:
# np.mgrid
# directly provides matrices full of indices for cases 
# where we can’t (or don’t want to) benefit from broadcasting:

In [198]:
x, y = np.mgrid[0:4, 0:4]

In [199]:
x

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [200]:
y

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [201]:
# Array shape manipulation

In [202]:
# Flattening

In [203]:
a=np.array([[2,1,3],[5,7,8]])
a

array([[2, 1, 3],
       [5, 7, 8]])

In [204]:
a.ravel()

array([2, 1, 3, 5, 7, 8])

In [205]:
a.T

array([[2, 5],
       [1, 7],
       [3, 8]])

In [206]:
a.T.ravel()

array([2, 5, 1, 7, 3, 8])

In [207]:
# Reshaping
# The inverse operation to flattening:

In [208]:
a.shape

(2L, 3L)

In [209]:
b=a.ravel()
b

array([2, 1, 3, 5, 7, 8])

In [210]:
b=b.reshape(2,3)
b

array([[2, 1, 3],
       [5, 7, 8]])

In [211]:
type(b)

numpy.ndarray

In [212]:
b=b.reshape((2,3))
b

array([[2, 1, 3],
       [5, 7, 8]])

In [213]:
type(b)

numpy.ndarray

In [214]:
# ndarray.reshape may return a view (cf help(np.reshape))), or copy

In [215]:
b

array([[2, 1, 3],
       [5, 7, 8]])

In [216]:
a

array([[2, 1, 3],
       [5, 7, 8]])

In [217]:
b[0,0]=99

In [218]:
a

array([[99,  1,  3],
       [ 5,  7,  8]])

In [219]:
# Beware: reshape may also return a copy!:

In [234]:
a=np.zeros((3,2))
a


array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [235]:
b=a.T.reshape(3*2)
b

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [236]:
b[0]=9
a

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [237]:
b

array([ 9.,  0.,  0.,  0.,  0.,  0.])

In [238]:
# Adding a dimension
# Indexing with the np.newaxis object allows us to add an axis to an array

In [239]:
z=np.array([1,2,3])
z

array([1, 2, 3])

In [240]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [241]:
z[np.newaxis:,]

array([1, 2, 3])

In [242]:
# Dimension shuffling

In [246]:
a=np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [257]:
a[2,2,1 ]

17

In [258]:
b = a.transpose(1, 2, 0)

In [261]:
b.shape            #doubt

(3L, 2L, 4L)

In [260]:
b[2, 1, 0]

5

In [266]:
# Resizing
# Size of an array can be changed with ndarray.resize:

In [265]:
a = np.arange(4)
a
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [269]:
# a.resize((4,))

In [220]:
# Sorting data

In [221]:
a = np.array([[4, 3, 5], [1, 2, 1]])

In [222]:
a=np.sort(a,axis=1) #latitudely
a

array([[3, 4, 5],
       [1, 1, 2]])

In [223]:
a=np.sort(a,axis=0)#longitudely
a

array([[1, 1, 2],
       [3, 4, 5]])

In [224]:
# Sorting with fancy indexing:
a=np.array([4,3,1,2])
j=np.argsort(a) #Returns the indices that would sort an array.
j

array([2, 3, 1, 0], dtype=int64)

In [225]:
a[j]

array([1, 2, 3, 4])

In [226]:
max=np.argmax(a)
max

0

In [227]:
a[max]

4

In [228]:
#similarly min

In [270]:
>>> a = np.array([4, 3, 1, 2])
>>> j_max = np.argmax(a)
>>> j_min = np.argmin(a)
>>> j_max, j_min

(0, 2)

In [271]:
#summary

In [ ]:
# Adjust the shape of the array using reshape or flatten it with ravel.